# Generated by Django 5.1.1 on 2024-09-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodplace',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='foodplace',
            name='added_on',
        ),
        migrations.AddField(
            model_name='foodplace',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='foodplace',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodplace',
            name='user_ratings_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
