# Generated by Django 5.1.1 on 2024-09-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_remove_foodplace_added_by_remove_foodplace_added_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodplace',
            name='cuisine_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='foodplace',
            name='opening_hours',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodplace',
            name='photo_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foodplace',
            name='place_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
